content:
  source:
    git:
      branch:
        fallback: master
        target: release-{MAJOR}.{MINOR}
      url: git@github.com:openshift/cluster-ingress-operator.git
container_yaml:
  go:
    modules:
    - module: github.com/openshift/cluster-ingress-operator
from:
  builder:
  - stream: golang
  member: openshift-enterprise-base
name: openshift/ose-cluster-ingress-operator
owners:
- aos-network-edge@redhat.com
required: true
